package co.templex.banbot.discord;

import de.btobastian.javacord.entities.message.embed.EmbedBuilder;

import java.awt.*;

public class Util {

    private Util() {
        throw new UnsupportedOperationException("Instantiation not permitted.");
    }

    /**
     * Builds an embedded message (modified from Moudoux/DiscordSelfBot)
     *
     * @param title       Title of the embed.
     * @param description Description of the embed.
     * @param footer      Footer of the embed.
     * @param image       Image of the embed.
     * @param thumbnail   Thumbnail of the embed.
     * @param color       Color of the embed.
     * @return emb The embed builder instance generated by this function.
     */
    public static EmbedBuilder generateEmbedBuilder(final String title, final String description, final String footer,
                                                    final String image, final String thumbnail, final Color color) {
        final EmbedBuilder emb = new EmbedBuilder();
        if (title == null) {
            return null;
        }
        emb.setTitle(title);
        if (description != null)
            emb.setDescription(description);
        if (footer != null)
            emb.setFooter(footer);
        if (image != null)
            emb.setImage(image);
        if (thumbnail != null)
            emb.setThumbnail(thumbnail);
        if (color != null)
            emb.setColor(color);
        else
            emb.setColor(Color.RED);
        return emb;
    }

}
